server:
  port: 8080
  servlet: 
    context-path: /gardsafe
    
springdoc:
  swagger-ui:
    enabled: true
    
spring:
  mvc:
    pathmatch:
      matching-strategy: ant-path-matcher
  debug: false
  datasource:
    url: jdbc:h2:mem:mydb
    username: sa
    password: password
    driverClassName: org.h2.Driver
  jpa:
    spring.jpa.database-platform: org.hibernate.dialect.H2Dialect 
  